package com.dynamodb.demo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "products")
public class Product {

    public static final String CATEGORY_INDEX = "id-category-index";

	@DynamoDBHashKey(attributeName = "id") 
    @DynamoDBAutoGeneratedKey              
    private String id;

    @DynamoDBAttribute(attributeName = "name") 
    private String productName;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = CATEGORY_INDEX)
    private String category;

    @DynamoDBAttribute(attributeName = "price")
    private float price;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public float getPrice() {
		return price;
	}

	public void setPrice(float price) {
		this.price = price;
	}


}
