<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Presence Sleep Development</title>
</head>
<body>
<div>Hi ${username},<div>
<div>Here is the confirmation code <b>${otp}</b> to verify your Email Account</div>
<br>
<div>We are here to help. </div>
</br>
<br/>
<div> Your Open Exchange Team!</div>
</body>
</html>